[modpack]

name = "manufaktur"
version = "1.2"

[mods]

angelsinfiniteores = "*"
angelsrefining = "*"
angelspetrochem = "*"
angelssmelting = "*"
#angelsbioprocessing = "*"
#angelslogistics = "*"
bobassembly = "*"
bobelectronics = "*"
bobenemies = "*"
bobgreenhouse = "*"
bobinserters = "*"
boblibrary = "*"
boblogistics = "*"
bobmining = "*"
bobmodules = "*"
bobores = "0.16.2"
bobplates = ">= 0.16.0"
bobpower = "*"
bobrevamp = "*"
bobtech = "*"
bobvehicleequipment = "*"
bobwarfare = "*"
SpaceMod = "*"
rso-mod = "*"
Bottleneck = "*"
upgrade-planner = "*"
Train_Ore_Color-016 = "*"
autofill = "*"
what-is-it-really-used-for = "*"
helmod = "*"
always-show-recipe-products = "*"